# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  development_repo: frontend

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

# panel for openstreetmap
panel_custom:
  - name: OpenStreetMap-panel
    # url_path needs to be unique for each panel_custom config
    url_path: redirect-server-controls
    sidebar_title: OpenStreetMap
    sidebar_icon: mdi:map
    module_url: /local/openStreetMap-panel.js
    config:
      # Data you want to make available to panel
      hello: world
